version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: asadoconkimchi-bitcoin-node-visualizer_app_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  app:
    image: ghcr.io/asadoconkimchi/bitcoin-node-visualizer:v1.4.1
    restart: on-failure
    stop_grace_period: 1m
    environment:
      BITCOIN_RPC_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_RPC_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $APP_BITCOIN_RPC_PASS
      BITCOIN_ZMQ_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_ZMQ_RAWBLOCK_PORT: 28332
      BITCOIN_ZMQ_RAWTX_PORT: 28333
      PORT: 3000
      NODE_ENV: production
